var head = [
    "Lockjaw",
    "3x3 eyes",
    "Cute'n'Round",
    "Goooogly",
    "Hole",
    "Grinder",
    "It Doesn't Look Right?",
    "Mandibles",
    "Cyclopian",
    "Fish Bowl!",
    "It Looks Dangerous",
    "Sees All",
    "Broken",
    "Looking Cool",
    "Spikey",
    "Baaaad Breath!",
    "HOT!!!",
    "Scary",
    "Bones",
    "God-like!!!"
];

var body = [
    "Belly-Full",
    "Missing Parts?",
    "Skewered",
    "Should it be Leaking?",
    "Brick Sh*thouse",
    "Rustgod",
    "Heavy Smoker",
    "Big Boned",
    "Beanpole",
    "Alien",
    "Riveting!!!",
    "Too Many Wires",
    "HR Giger",
    "Seen Better Days",
    "Carapaced",
    "All Chrome and Shiny",
    "Spikes",
    "All Dressed Up",
    "Speed Holes",
    "Death"
];

var arms = [
    "Beeeefy",
    "Hydraulic!!!",
    "Extras!!!",
    "Probably toooo long…",
    "Stubby",
    "Noodle!!",
    "One Armed Bandit",
    "Knuckle Dragger",
    "Mr Tickle",
    "Double Jointed",
    "Too Many",
    "Triple Jointed",
    "Fancypants",
    "Pistons",
    "Long + Thin",
    "Armoured!!!",
    "Mismatched",
    "Spider-Like",
    "Wired",
    "War Machine!"
];

var hands = [
    "Hands are Hard!!!",
    "Claws are Easy",
    "Buzzzzzzzzz",
    "Take an eye out with that",
    "Kabooom!",
    "Grip",
    "Barbed",
    "Up Yours",
    "What a Knockout!",
    "Biggun",
    "Scorcher",
    "Electric",
    "Hook",
    "Two Handed",
    "Buster",
    "Calamari",
    "Knuckles",
    "Creepy",
    "Old Witch Hands",
    "Guns",
];

var legs = [
    "Nice Pins",
    "Leg Day!",
    "Spidey",
    "Tank Tracks",
    "Ballerina",
    "Quadropod",
    "Tri-pod",
    "Who Needs Legs?",
    "Centaur",
    "Sticks",
    "Dash!!",
    "Stumpy",
    "They Call Me Wheels",
    "Centipede",
    "Bones",
    "Weak",
    "Pistons",
    "Daddy Long",
    "Triple Jointed",
    "Backwards"
];

var flavour = [
    "Rusty",
    "Polished",
    "Ronin",
    "Beaten",
    "Mouldy",
    "Savage",
    "Holy",
    "Evil",
    "Too Many Spikes",
    "Jagged",
    "Soft",
    "Sleeeek",
    "Unlucky",
    "Dirty",
    "Cosmic",
    "Weirdo",
    "Cutey",
    "Asymetrical",
    "Killing Machine!!",
    "Is That Meat!?!"
];

var adjectives = [
    "Ambitious",
    "Amiable",
    "Analytical",
    "Artistic",
    "Assertive",
    "Benevolent",
    "Brilliant",
    "Cautious",
    "Charismatic",
    "Charming",
    "Compassionate",
    "Confident",
    "Courageous",
    "Creative",
    "Cunning",
    "Curious",
    "Daring",
    "Diligent",
    "Eccentric",
    "Eloquent",
    "Empathetic",
    "Enigmatic",
    "Fearless",
    "Fierce",
    "Generous",
    "Gregarious",
    "Humble",
    "Inquisitive",
    "Intrepid",
    "Jovial",
    "Meticulous",
    "Mischievous",
    "Nurturing",
    "Optimistic",
    "Passionate",
    "Persistent",
    "Pragmatic",
    "Quirky",
    "Resourceful",
    "Resilient",
    "Savvy",
    "Sincere",
    "Sophisticated",
    "Stoic",
    "Tenacious",
    "Thoughtful",
    "Unconventional",
    "Vibrant",
    "Witty",
    "Zealous",
    "Aloof",
    "Adventurous",
    "Arrogant",
    "Boisterous",
    "Calculating",
    "Cynical",
    "Devious",
    "Disgruntled",
    "Egotistical",
    "Fickle",
    "Gullible",
    "Impulsive",
    "Indecisive",
    "Insatiable",
    "Jealous",
    "Lethargic",
    "Manipulative",
    "Narcissistic",
    "Obstinate",
    "Overbearing",
    "Pessimistic",
    "Reckless",
    "Reserved",
    "Skeptical",
    "Stubborn",
    "Superficial",
    "Tactless",
    "Timid",
    "Unpredictable",
    "Vindictive",
    "Whimsical",
    "Wistful",
    "Zany",
    "Apathetic",
    "Belligerent",
    "Callous",
    "Defiant",
    "Evasive",
    "Foolhardy",
    "Grumpy",
    "Hesitant",
    "Impatient",
    "Indifferent",
    "Languid",
    "Melancholic",
    "Nonchalant",
    "Obnoxious",
    "Pernicious",
    "Loyal",
    "Quizzical"
];

var names = [
    "Alex",
    "Avery",
    "Bailey",
    "Blair",
    "Cameron",
    "Casey",
    "Charlie",
    "Dakota",
    "Devon",
    "Ellis",
    "Emery",
    "Finley",
    "Harper",
    "Hayden",
    "Indigo",
    "Jaden",
    "Jordan",
    "Kai",
    "Lane",
    "Linden",
    "Morgan",
    "Parker",
    "Quinn",
    "Reese",
    "Riley",
    "Rowan",
    "Sage",
    "Skyler",
    "Sutton",
    "Taylor",
    "Val",
    "Wren",
    "Zephyr",
    "Adair",
    "Arden",
    "Ash",
    "Blaise",
    "Cai",
    "Darcy",
    "Eden",
    "Frost",
    "Gale",
    "Harbor",
    "Ira",
    "Jules",
    "Kiran",
    "Lake",
    "Marlowe",
    "Nico",
    "Ocean",
    "Peyton",
    "Quincy",
    "Rey",
    "Sasha",
    "Taj",
    "Umber",
    "Vesper",
    "Wynn",
    "Xan",
    "Yael",
    "Zion",
    "Amari",
    "Blaise",
    "Cai",
    "Dakota",
    "Ezri",
    "Finn",
    "Gray",
    "Hollis",
    "Izzy",
    "Jory",
    "Kai",
    "Lior",
    "Mica",
    "Nori",
    "Onyx",
    "Pax",
    "Quill",
    "Remy",
    "Sage",
    "Tate",
    "Uri",
    "Vale",
    "Wynn",
    "Xen",
    "Yael",
    "Zephyr",
    "Ara",
    "Briar",
    "Cedar",
    "Dune",
    "Echo",
    "Fable",
    "Garnet",
    "Haven",
    "Ivory",
    "Jazz",
    "Kestrel",
    "Lark",
    "Moss"
];

function shuffle(array) {
    let currentIndex = array.length,  randomIndex;
  
    // While there remain elements to shuffle.
    while (currentIndex > 0) {
  
      // Pick a remaining element.
      randomIndex = Math.floor(Math.random() * currentIndex);
      currentIndex--;
  
      // And swap it with the current element.
      [array[currentIndex], array[randomIndex]] = [
        array[randomIndex], array[currentIndex]];
    }
  
    return array;
}

function generateRobot(){
    //called on "generate" from site
    let randomHead = shuffle(head);
    let randomBody = shuffle(body);
    let randomArms = shuffle(arms);
    let randomHands = shuffle(hands);
    let randomLegs = shuffle(legs);
    let randomFlavour = shuffle(flavour);
    let randomAdjectives = shuffle(adjectives);
    let randomNames = shuffle(names);
    let xml = document.implementation.createDocument("", "", null);
    let numRobot = document.getElementById("numRobots").attributes.value;

    var roster = xml.createElement("roster");
    for(i = 0; i <= numRobot; i++){
        var robot = xml.createElement("robot" + i);
        robot.setAttribute("name", (randomAdjectives[i] + " " + randomNames[i]));
        robot.appendChild("flavour", randomFlavour[i]);
        robot.appendChild("head", randomHead[i]);
        robot.appendChild("body", randomBody[i]);
        robot.appendChild("arms", randomArms[i]);
        robot.appendChild("hands", randomHands[i]);
        robot.appendChild("legs", randomLegs[i]);
        xml.appendChild(robot);
    }
}